---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyzer(analyzer)
	extract_formatting(extract_formatting)
	word_tool(word_tool)
	pdf_tool(pdf_tool)
	notification(notification)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyzer;
	analyzer --> extract_formatting;
	extract_formatting -.-> pdf_tool;
	extract_formatting -.-> word_tool;
	pdf_tool --> notification;
	word_tool --> notification;
	notification --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
